In [1]:
import sys
import pandas as pd

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("Kernel funcionando correctamente ✅")

Python: 3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)]
Pandas: 3.0.6
Kernel funcionando correctamente ✅

In [2]:
df = pd.read_csv("../data/raw/ObesityDataSet_raw_and_data_sinthetic.csv")

print("Registros:", df.shape[0])
print("Variables:", df.shape[1])

df.head()

Registros: 2111
Variables: 17

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [3]:
print("Registros:", df.shape[0])
print("Variables:", df.shape[1])
print("Valores faltantes:", df.isnull().sum().sum())
print("Registros duplicados:", df.duplicated().sum())

df[
    [
        "Gender",
        "Age",
        "Height",
        "Weight",
        "FAF",
        "TUE",
        "MTRANS",
        "NObeyesdad"
    ]
].head(10)

Registros: 2111
Variables: 17
Valores faltantes: 0
Registros duplicados: 24

,Gender,Age,Height,Weight,FAF,TUE,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,0.0,1.0,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,3.0,0.0,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,2.0,1.0,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,2.0,0.0,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,0.0,0.0,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,0.0,0.0,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,1.0,0.0,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,3.0,0.0,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,1.0,1.0,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,1.0,1.0,Public_Transportation,Normal_Weight